plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'com.resumetailor'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
    targetCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.3'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.4'
    implementation 'com.google.code.gson:gson:2.10.1'

    implementation 'org.apache.pdfbox:pdfbox:3.0.1'
    implementation 'org.apache.pdfbox:fontbox:3.0.1'

    implementation platform('software.amazon.awssdk:bom:2.25.0')
    implementation 'software.amazon.awssdk:ses'
    implementation 'software.amazon.awssdk:s3'
    implementation 'software.amazon.awssdk:dynamodb'
    implementation 'software.amazon.awssdk:bedrockruntime'
    implementation 'software.amazon.awssdk:url-connection-client'

    implementation 'com.sun.mail:jakarta.mail:2.0.1'
    implementation 'org.slf4j:slf4j-simple:2.0.9'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

shadowJar {
    archiveClassifier.set('aws')
    mergeServiceFiles()
}

tasks.named('build') {
    dependsOn shadowJar
}
