package com.resumetailor.handler;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.google.gson.Gson;
import com.resumetailor.model.EmailRequest;
import com.resumetailor.service.EmailService;

import java.util.Map;

public class SendEmailHandler implements RequestHandler<Map<String, Object>, Map<String, Object>> {

    private final Gson gson = new Gson();
    private final EmailService emailService = new EmailService();

    @Override
    public Map<String, Object> handleRequest(Map<String, Object> input, Context context) {
        try {
            String body = (String) input.get("body");
            EmailRequest request = gson.fromJson(body, EmailRequest.class);

            if (request == null || request.email() == null || request.email().isBlank()) {
                return Map.of(
                        "statusCode", 400,
                        "headers", Map.of("Content-Type", "application/json", "Access-Control-Allow-Origin", "*"),
                        "body", gson.toJson(Map.of("error", "email is required"))
                );
            }

            emailService.sendEmailWithAttachment(
                    request.email(),
                    request.pdfBase64(),
                    request.coverLetterPdfBase64(),
                    "Your Tailored Resume",
                    "Here is your tailored resume package generated by ATS Resume Tailor.",
                    request.jobUrl()
            );

            return Map.of(
                    "statusCode", 200,
                    "headers", Map.of("Content-Type", "application/json", "Access-Control-Allow-Origin", "*"),
                    "body", gson.toJson(Map.of("message", "Email sent successfully"))
            );

        } catch (Exception e) {
            return Map.of(
                    "statusCode", 500,
                    "headers", Map.of("Content-Type", "application/json", "Access-Control-Allow-Origin", "*"),
                    "body", gson.toJson(Map.of("error", e.getMessage()))
            );
        }
    }
}
